const speakers = [
  {
    id: 1,
    path: "",
    photo: "/speakers/karolAttekita.png",
    name: "Karol Attekita",
    tech: "Carreira e desenvolvimento pessoal",
    topic: "",
    mini_bio: "Karol é engenheira de software especialista em aplicativos e games, com mais de 13 anos de experiência e 5 prêmios de reconhecimento nacional. Foi eleita LinkedIn Top Voice 2023 pelo seu trabalho de criação de conteúdo para a comunidade de tecnologia. Em 2022 esteve na lista dos 50 hackers to follow e foi indicada para o prêmio internacional 'Women that build'. Atuou por quase 10 anos como freelancer para equipes multinacionais e possui mais de 20 aplicativos e jogos publicados na App Store. Atualmente é Engenheira iOS na Riot Games (pela X-team) e compartilha conteúdo no canal Attekita Dev onde impacta em suas redes sociais mais de 240 mil pessoas. Acredita que podemos mudar o mundo com o poder da informação!",
    title: "",
    companyTitle: "Riot Games (via X-team)",
    social_media: {
      instagram: "https://www.instagram.com/attekitadev/",
      twitter: "https://twitter.com/AttekitaBullas",
      linkedIn: "https://www.linkedin.com/in/bullas-attekita/",
      github: "https://github.com/Bullas",
      website: "https://www.attekita.com/",
    },
  },
  {
    id: 2,
    path: "",
    photo: "/speakers/andressaFreires.png",
    name: "Andressa Freires",
    tech: "IA Generativa",
    topic: "Eu trago a vocês um aspecto fundamental do nosso cenário digital em rápida evolução: a importância da alfabetização digital no contexto da Inteligência Artificial (IA). Numa era em que a tecnologia permeia todas as facetas das nossas vidas, garantir que pessoas de diversas origens estejam equipadas com as competências necessárias para navegar e compreender a IA não é apenas uma opção, é uma necessidade.",
    mini_bio: "Negra, periférica, cientista e professora. Sr Data Scientist. Professora de pós e cursos livres. Fundadora da diversiData. Voluntária e ativista em comunidades que inserem diversidade em tech. Palestrante sobre ética, AI, Data Science e Diversidade, Equidade e Inclusão. Valuable Young Leader pelo Instituto Anga e MIT Sloan Review. 1o lugar no reconhecimento Global Ada Lovelace para mulheres em tech. 50 to follow na Gama Academy em Data & BI. Especialista em Data Science convidada para inclusão da profissão de Data Science na CBO (Classificação Brasileira de Ocupações) pelo Ministério do Trabalho e USP. Integrante do Global Shapers do Fórum Econômico Mundial.",
    title: "O papel crucial da alfabetização digital em IA",
    companyTitle: "diversiData",
    social_media: {
      instagram: "https://www.instagram.com/dessafreires/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/andressafreires/",
      github: "",
      website: "https://www.youtube.com/c/diversiData",
    },
  },
  {
    id: 3,
    path: "",
    photo: "/speakers/kamilaSantos.png",
    name: "Kamila Santos",
    tech: "Tecnologias web",
    topic: "Uma das habilidades que mais foi responsável por eu crescer na carreira foi o conhecimento em arquitetura e system design, nessa palestra irei te ensinar quais os tópicos voce precisa se preocupar quando falamos de system design e inclusive ensinar na prática como seria a arquitetura de um backend de ecommerce, vamos cobrir assuntos como : requisitos, banco de dados, cache, arquitetura orientada a eventos, monitoramento, observabilidade, e muito mais!",
    mini_bio: "Desenvolvedora especialista que estuda programação desde 2013, especialista na stack: Java, Spring, AWS e Microsserviços. Vasta experiências em empresas do setor financeiro, atuando tanto como consultora e como funcionária. Também crio conteúdo desde 2018, somos mais de 3000 alunos em cursos e mentorias, já palestrei em grandes conferências internacionais como Java Global Summit, We are devs - Java developer day, Jlove conference e em grandes eventos nacionais como Codecon, The Developers Conference e Campus Party. Premiada pela Microsoft como Microsoft MVP há 3 anos , co-autora de 3 livros e criadora de conteúdo no YouTube e Instagram kamila_code.",
    title: "System Design 101: Tudo que você precisa saber ao definir arquiteturas",
    companyTitle: "Zup Innovation",
    social_media: {
      instagram: "https://www.instagram.com/kamila_code/",
      twitter: "https://twitter.com/kamila_code",
      linkedIn: "https://www.linkedin.com/in/kamila-santos-oliveira/",
      github: "https://github.com/Kamilahsantos",
      website: "https://beacons.ai/kamila_code",
    },
  },
  {
    id: 4,
    path: "",
    photo: "/speakers/vanessaSousa.png",
    name: "Vanessa Sousa",
    tech: "UX/UI",
    topic: "Você já se perguntou como os dados podem transformar a maneira como projetamos experiências para os usuários? Nesta palestra, exploramos o papel fundamental dos dados no design de experiência do usuário (UX). Desde os fundamentos dos dados até sua aplicação prática no processo de design, mergulhamos em como os dados podem informar e aprimorar cada etapa do ciclo de vida de um produto ou serviço digital.",
    mini_bio: "UX Writer, Designer, Desenvolvedora e Curadora de IAs Conversacionais, Tutora, Palestrante e Voluntária. Formada em Análise e Desenvolvimento de Sistemas e fruto de transição de carreira. Casada, mãe de pet, aquariana, geek, techmaromba, ama shows, comida e Coca Cola.",
    title: "Fundamentos de dados no contexto de UX Design",
    companyTitle: "Capgemini",
    social_media: {
      instagram: "https://www.instagram.com/vua_nessa/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/vanessa20sousa/",
      github: "",
      website: "https://linktr.ee/vuanessa",
    },
  },
  {
    id: 5,
    path: "",
    photo: "/speakers/kamillaCerqueira.png",
    name: "Kamilla Cerqueira",
    tech: "Carreira e desenvolvimento pessoal",
    topic: "Na palestra 'Liderança Feminina na Tecnologia: Conquistando Espaço e Inspirando Transformação', compartilho minha própria jornada como exemplo vivo dos desafios e oportunidades enfrentados pelas mulheres na indústria da tecnologia. Ao longo da minha carreira, enfrentei barreiras e preconceitos, mas também encontrei apoio e mentoria que me ajudaram a superar esses obstáculos.",
    mini_bio: "Sou Kamilla Cerqueira, profissional apaixonada pela área de Customer Success e comprometida em criar experiências excepcionais para os clientes. Com 15 anos de experiência na indústria, atuo em uma área Cross de Customer Success, onde colaboro com equipes multidisciplinares para garantir o sucesso dos clientes. Minha jornada profissional tem sido marcada por desafios e conquistas, que me ensinaram a importância da resiliência, da colaboração e do desenvolvimento contínuo. Ao longo dos anos, tive a oportunidade de trabalhar em diferentes contextos e empresas, sempre buscando agregar valor aos clientes e promover um ambiente de trabalho saudável. Fora do ambiente de trabalho, gosto de viajar, assistir séries, ter momentos de lazer com minha família. Estou sempre em busca de novas formas de aprender e crescer, tanto pessoal quanto profissionalmente.",
    title: "Liderança feminina na tecnologia: conquistando espaço e inspirando transformação",
    companyTitle: "MáximaTech",
    social_media: {
      instagram: "https://www.instagram.com/kamilla.cerqueira/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/kamilla-cerqueira",
      github: "",
      website: "",
    },
  },
  {
    id: 6,
    path: "",
    photo: "/speakers/adrienneMendes.png",
    name: "Adrienne Mendes",
    tech: "Carreira e desenvolvimento pessoal",
    topic: "Foco em como otimizar os estudos em inglês, com dicas práticas , para que você alcance a fluência e conquiste a tão sonhada vaga que exige inglês fluente. De modo leve , didático e usando metodologias ativas a palestra é bem instigante e motivadora. Também levarei brindes para garantir a interação da plateia. Vai ser show! Let's rock!",
    mini_bio: "Profissional com mais de 20 anos de experiência na área de gestão de projetos, negócios e educação. Especialista em Planejamento & Gestão de Projetos. Gestora com ênfase em Turismo & Hotelaria. Licenciada em Letras Português - Inglês. Certificada Scrum Master, White Belt e em Gestão Neurocomportamental de Projetos. Fluente em Inglês e Espanhol. Iniciou sua carreira como professora de idiomas (Inglês e Espanhol) na Educação Básica, EJA e Ensino Superiour. Atuou no Sistema S (Sesi, FIEG e Senac) como líder de projetos. Voluntária pelo PMI DF (gerente de projetos do programa de mentoring) e pelo PMI GO (membro do time do PM Thanks Mulher). Membro do Elas Projetam e do Mulheres GO.",
    title: "Inglês & TI: eleve a sua carreira a outro nível",
    companyTitle: "Ipasgo",
    social_media: {
      instagram: "https://www.instagram.com/adriennecmendes/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/adrienne-mendes",
      github: "",
      website: "",
    },
  },
  {
    id: 7,
    path: "",
    photo: "/speakers/fernandaKelly.png",
    name: "Fernanda Kelly",
    tech: "Diversidade e inclusão",
    topic: "Nós planejamos abordar a sub-representação de grupos étnicos minoritários em espaços e posições da área de TI. Temos em mente um tempo médio de 30 minutos, mas se o público presente estiver engajado, acreditamos que em no máximo 50 minutos a palestra chegue ao fim. O tópico de embasamento de todo o desenrolar da palestra é: Quantas líderes pretas você já teve? Quantas estão no seu time?",
    mini_bio: "Sou uma mulher preta. Uma mulher preta com coragem, sabe? Que é graduada em Estatística pela UFG, 'brincou' de fazer mestrado em Ciências da Computação pela mesma universidade, mas que acabou indo trabalhar na área da saúde e iniciou o mestrado em Sistemas Inteligentes e suas Aplicações na Saúde pela UFCSPA. Também sou fundadora de um capítulo da organização mundial R-Ladies e faço parte do time global da organização AI Inclusive. E sabe o que é bom nisso tudo? É que caminho caminho ao lado de grandes mulheres.",
    title: "Observar e absorver, em qual momento a diversidade atinge você?",
    companyTitle: "Fundação Getulio Vargas",
    social_media: {
      instagram: "https://www.instagram.com/fernandakellyrs",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/fernanda-kelly-98a43b17a",
      github: "https://github.com/FernandaKelly",
      website: "https://www.fernandakellyrs.com/",
    },
  },
  {
    id: 8,
    path: "",
    photo: "/speakers/camisMoreira.png",
    name: "Camis Moreira",
    tech: "Carreira e desenvolvimento pessoal",
    topic: "TI na boca do povo é só alegria, mas só quem está ou pretende entrar na área da tecnologia sabe o quanto esse setor pode ser desafiador. Falar algumas verdades, acolher preocupações e expor oportunidades é o objetivo dessa palestra, falar sobre minha trajetória e como a minha experiência pode te auxiliar a dar um tranco na sua carreira!",
    mini_bio: "Camis é uma pessoa não binária, palestrante, educadora, líder de comunidade e especialista em E-commerce e Frontend. Atua como analista sênior na Object Edge e possui certificação Google Project Management, além de desempenhar um papel crucial na liderança de times e no desenvolvimento de pessoas na área tech, participando ativamente em projetos de grande escala nacionais e internacionais.",
    title: "Testemunhos de TI: Estratégias de carreira para quem é da área de tecnologia",
    companyTitle: "Object Edge",
    social_media: {
      instagram: "https://www.instagram.com/camiiismoreira",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/camismoreira",
      github: "",
      website: "https://linktr.ee/camismoreira",
    },
  },
  {
    id: 9,
    path: "",
    photo: "/speakers/jaquelineRibeiro.png",
    name: "Jaqueline Ribeiro",
    tech: "IoT, Acessibilidade",
    topic: "A palestra que explora como a combinação da Internet das Coisas (IoT) e da tecnologia assistiva está revolucionando a acessibilidade para pessoas com deficiência. Nesta apresentação envolvente, destacamos como dispositivos conectados à IoT e tecnologias assistivas estão sendo integrados para criar soluções inovadoras que melhoram a qualidade de vida e a independência desses indivíduos. Exploramos exemplos práticos de como a IoT está sendo aplicada em diversas áreas, como casas inteligentes, mobilidade urbana e saúde, para proporcionar uma experiência mais acessível e inclusiva.",
    mini_bio: "Professora e pesquisadora no IF Goiano Campus Ceres. Se dedica na pesquisa, ensino e extensão com temas relacionados a Internet das Coisas (IOT), Inovação e Tecnologia assistiva. Graduada em Ciência da Computação (PUC-GO), Mestre em Ciências (UFU) e Doutora em Engenharia de Sistemas Eletrônicos e Automação (UnB). Coordenadora dos cursos técnicos em Informática e do Núcleo de tecnologia e Inovação do Campus Ceres. No ensino ministra disciplinas no ensino técnico, graduação e pós -graduação. Founder da Comunidade MulheresGo, Líder da Comunidade StartupGO, Mentora voluntária da Techstars startup weekend, Campus Party, Latinoware e Nasa. Mentora de Inovação de Goiás.",
    title: "Acessibilidade ampliada: desvendando o potencial da IoT e tecnologia assistiva",
    companyTitle: "IF Goiano",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/jaqueline-ribe",
      github: "",
      website: "",
    },
  },
  {
    id: 10,
    path: "",
    photo: "/speakers/emmanuelleRichard.png",
    name: "Emmanuelle Richard",
    tech: "Quality Assurance",
    topic: "A cultura de testes se torna cada vez mais importante para empresas a cada ano. Diante de tantas mudanças e incertezas em nível global, é cada vez maior a exigência de antecipar riscos e reagir às transformações para manter a competitividade dos negócios.",
    mini_bio: "Eu sou deste milênio. Sou potiguar e aos 7 anos, comecei a vender chocolates na escola em Natal/RN. Aos 12 anos desenvolvi meu primeiro aplicativo, aos 15 ingressei na Faculdade de Ciência da Computação e aos 19 iniciei a pós-graduação em Engenharia de Dados na PUC. Atualmente tenho 21 anos e trabalho como Engenheira de Qualidade. Sempre busquei criar oportunidades, tive uma startup, trabalhei como desenvolvedora freelancer e também atuei em empresas de tecnologia desde software house até startups, além de coordenar o projeto W3E - Women Winning the World with Equity, que visa instigar e apoiar as mulheres a alcançarem o lugar que desejam. Já lecionei em diversos eventos como Campus Party, FLISOL, PhP Experience, RubyConf, DevFest, Festival Path, OAB/RN e outros, inspirando e instigando jovens e adultos a se desenvolverem como cidadãos, tornando-se protagonistas de suas próprias histórias, como incentivá-los a ter uma atitude empreendedora e protagonista. Mostrando também que programar é uma atividade divertida e fascinante.",
    title: "Quality Assurance: Mais do que apenas busca de bugs na interface.",
    companyTitle: "Gradus",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/manurichard/",
      github: "",
      website: "",
    },
  },
  {
    id: 11,
    path: "",
    photo: "/speakers/elisianeSouza.png",
    name: "Elisiane Souza",
    tech: "Carreira e desenvolvimento pessoal",
    topic: "A mensagem que quero passar é “ Como começar na área de TI” pra onde olhar e como olhar. E dessa forma conseguir traçar um estratégia pra construir a própria carreira, por que aliás esse é o nosso maior negócio! ",
    mini_bio: "Oie! Eu sou a Elisiane, mas todo mundo me chama de Lise, tenho 24 anos sou analista de suporte na ACSoftware e na finalzinho do ano passado fui convidada pra ser sócia dos meus chefes na nossa nova holding que é a ACSMSP que presta serviços gerenciados dos softwares que vendemos. Tenho bem pouco tempo de carreira e estou aprendendo a olhar pra TI como um todo e gerenciar minha própria carreira. Hoje meu objetivo é me desenvolver mais na área de governança e partes estratégicas de negócios. ",
    title: "Como começar na área de TI",
    companyTitle: "ACSoftware",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/elisiane-de-souza-401836209",
      github: "",
      website: "",
    },
  },
  {
    id: 12,
    path: "",
    photo: "/speakers/alexiaKattah.png",
    name: "Alexia Kattah",
    tech: "Tecnologias web, Infra/DevOps",
    topic: "Nessa palestra, irei apresentar outras possibilidades de implementações serverless sem necessariamente usar AWS Lambda. Aqui, vou mostrar como implementar os microserviços com uma arquitetura serverless, como analisar e metrificar o funcionamento das APIs.",
    mini_bio: "Senior software engineer com mais de 8 anos de experiência, mineira, criou os primeiros códigos com 11 anos, mãe de pet e viciada em friends.",
    title: "Implementando seus microserviços serverless ",
    companyTitle: "Khipo",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/alexiakattah/",
      github: "",
      website: "",
    },
  },
  {
    id: 13,
    path: "",
    photo: "/speakers/alyceSuza.png",
    name: "Alyce Suza",
    tech: "Cibersegurança",
    topic: "Na palestra, abordarei diversos aspectos para desmistificar a área de cibersegurança, desde a explicação das subáreas tecnológicas até detalhes sobre o que estudar e como ingressar nesse mundo do hacking. Vou discutir as diferenças entre cibersegurança defensiva e ofensiva, esclarecendo o que fazem aqueles que defendem sistemas e os que os atacam. Além disso, apresentarei exemplos práticos para ilustrar conceitos importantes. Também destacarei como o conhecimento em cibersegurança pode beneficiar profissionais de desenvolvimento de software e como a cibersegurança está sendo aplicada em diversas outras áreas além da tecnologia.",
    mini_bio: "Sou a Alyce Suza, Analista de Cibersegurança Ofensiva - Red Team. Adoro explorar os cantos mais sombrios da internet... tudo em nome da segurança, é claro! Com habilidades afiadas em hacking em ambientes web e mobile, e uma sólida experiência em gestão de vulnerabilidades, mantenho a segurança digital em alta enquanto mantenho o bom humor. Desde a infância, a tecnologia é minha paixão, e estou sempre em eventos e palestras, compartilhando conhecimento de forma divertida e informativa. Então, se você quer aprender sobre segurança cibernética enquanto se diverte, é só dar uma passada! Estou sempre pronta para uma boa conversa sobre o mundo digital.",
    title: "Desmistificando a área de Cibersegurança: como funciona e como entrar neste mundo do Hacking",
    companyTitle: "ALLOS",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/alyce-suza/",
      github: "",
      website: "",
    },
  },
  {
    id: 14,
    path: "",
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "",
    topic: "",
    mini_bio: "",
    title: "",
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
    },
  },
  {
    id: 15,
    path: "",
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "",
    topic: "",
    mini_bio: "",
    title: "",
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
    },
  },
  // {
  //   id: 16,
  //   path: "",
  //   photo: "/speakers/aDefinir.png",
  //   name: "A definir",
  //   tech: "Minha tecnologia",
  //   topic: "Tópico da minha palestra",
  //   mini_bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur officiis architecto dignissimos sed, consequuntur magnam, praesentium dicta voluptates nulla libero ut harum placeat reiciendis nobis velit, sequi facilis. Temporibus, sunt.",
  //   title: "Título da minha palestra",
  //   companyTitle: "Nome da minha empresa",
  //   social_media: {
  //     instagram: "https://www.instagram.com/gdggoiania/",
  //     twitter: "https://twitter.com/gdggoiania",
  //     linkedIn: "https://www.linkedin.com/company/gdggoiania/",
  //     github: "https://gitub.com/gdggoiania",
  //     website: "https://gdg.community.dev/gdg-goiania/",
  //   },
  // },
];

export default speakers;
