const speakers = [
  {
    id: 1,
    path: "",
    photo: "/speakers/karolAttekita.png",
    name: "Karol Attekita",
    tech: "Engenheira iOS",
    topic: "",
    mini_bio: "Karol é engenheira de software especialista em aplicativos e games, com mais de 13 anos de experiência e 5 prêmios de reconhecimento nacional. Foi eleita LinkedIn Top Voice 2023 pelo seu trabalho de criação de conteúdo para a comunidade de tecnologia. Em 2022 esteve na lista dos 50 hackers to follow e foi indicada para o prêmio internacional 'Women that build'. Atuou por quase 10 anos como freelancer para equipes multinacionais e possui mais de 20 aplicativos e jogos publicados na App Store. Atualmente é Engenheira iOS na Riot Games (pela X-team) e compartilha conteúdo no canal Attekita Dev onde impacta em suas redes sociais mais de 240 mil pessoas. Acredita que podemos mudar o mundo com o poder da informação!",
    title: "",
    companyTitle: "Riot Games (via X-team)",
    social_media: {
      instagram: "https://www.instagram.com/attekitadev/",
      twitter: "https://twitter.com/AttekitaBullas",
      linkedIn: "https://www.linkedin.com/in/bullas-attekita/",
      github: "https://github.com/Bullas",
      website: "https://www.attekita.com/",
    },
  },
  {
    id: 2,
    path: "",
    photo: "/speakers/andressaFreires.png",
    name: "Andressa Freires",
    tech: "Sr Data Scientist",
    topic: "Eu trago a vocês um aspecto fundamental do nosso cenário digital em rápida evolução – a importância da alfabetização digital no contexto da Inteligência Artificial (IA). Numa era em que a tecnologia permeia todas as facetas das nossas vidas, garantir que pessoas de diversas origens estejam equipadas com as competências necessárias para navegar e compreender a IA não é apenas uma opção; é uma necessidade.",
    mini_bio: "Negra, periférica, cientista e professora. Sr Data Scientist. Professora de pós e cursos livres. Fundadora da diversiData. Voluntária e ativista em comunidades que inserem diversidade em tech. Palestrante sobre ética, AI, Data Science e Diversidade, Equidade e Inclusão. Valuable Young Leader pelo Instituto Anga e MIT Sloan Review. 1o lugar no reconhecimento Global Ada Lovelace para mulheres em tech. 50 to follow na Gama Academy em Data & BI. Especialista em Data Science convidada para inclusão da profissão de Data Science na CBO (Classificação Brasileira de Ocupações) pelo Ministério do Trabalho e USP. Integrante do Global Shapers do Fórum Econômico Mundial.",
    title: "IA Generativa, Análise de dados, Carreira e desenvolvimento pessoal",
    companyTitle: "diversiData",
    social_media: {
      instagram: "https://www.instagram.com/dessafreires/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/andressafreires/",
      github: "",
      website: "https://www.youtube.com/c/diversiData",
    },
  },
  {
    id: 3,
    path: "",
    photo: "/speakers/kamilaSantos.png",
    name: "Kamila Santos",
    tech: "Backend Developer Specialist",
    topic: "",
    mini_bio: "Desenvolvedora especialista que estuda programação desde 2013, especialista na stack: Java, Spring, AWS e Microsserviços. Vasta experiências em empresas do setor financeiro, atuando tanto como consultora e como funcionária. Também crio conteúdo desde 2018, somos mais de 3000 alunos em cursos e mentorias, já palestrei em grandes conferências internacionais como Java Global Summit, We are devs - Java developer day, Jlove conference e em grandes eventos nacionais como Codecon, The Developers Conference e Campus Party. Premiada pela Microsoft como Microsoft MVP há 3 anos , co-autora de 3 livros e criadora de conteúdo no YouTube e Instagram kamila_code.",
    title: "",
    companyTitle: "Zup Innovation",
    social_media: {
      instagram: "https://www.instagram.com/kamila_code/",
      twitter: "https://twitter.com/kamila_code",
      linkedIn: "https://www.linkedin.com/in/kamila-santos-oliveira/",
      github: "https://github.com/Kamilahsantos",
      website: "https://beacons.ai/kamila_code",
    },
  },
  {
    id: 4,
    path: "",
    photo: "/speakers/vanessaSousa.png",
    name: "Vanessa Sousa",
    tech: "Dev/UX Writer",
    topic: "",
    mini_bio: "UX Writer, Designer, Desenvolvedora e Curadora de IAs Conversacionais, Tutora, Palestrante e Voluntária. Formada em Análise e Desenvolvimento de Sistemas e fruto de transição de carreira. Casada, mãe de pet, aquariana, geek, techmaromba, ama shows, comida e Coca Cola.",
    title: "",
    companyTitle: "Capgemini",
    social_media: {
      instagram: "https://www.instagram.com/vua_nessa/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/vanessa20sousa/",
      github: "",
      website: "https://linktr.ee/vuanessa",
    },
  },
  {
    id: 5,
    path: "",
    photo: "/speakers/kamillaCerqueira.png",
    name: "Kamilla Cerqueira",
    tech: "Customer Success",
    topic: "Na palestra 'Liderança Feminina na Tecnologia: Conquistando Espaço e Inspirando Transformação', compartilho minha própria jornada como exemplo vivo dos desafios e oportunidades enfrentados pelas mulheres na indústria da tecnologia. Ao longo da minha carreira, enfrentei barreiras e preconceitos, mas também encontrei apoio e mentoria que me ajudaram a superar esses obstáculos.",
    mini_bio: "Sou Kamilla Cerqueira, profissional apaixonada pela área de Customer Success e comprometida em criar experiências excepcionais para os clientes. Com 15 anos de experiência na indústria, atuo em uma área Cross de Customer Success, onde colaboro com equipes multidisciplinares para garantir o sucesso dos clientes. Minha jornada profissional tem sido marcada por desafios e conquistas, que me ensinaram a importância da resiliência, da colaboração e do desenvolvimento contínuo. Ao longo dos anos, tive a oportunidade de trabalhar em diferentes contextos e empresas, sempre buscando agregar valor aos clientes e promover um ambiente de trabalho saudável. Fora do ambiente de trabalho, gosto de viajar, assistir séries, ter momentos de lazer com minha família. Estou sempre em busca de novas formas de aprender e crescer, tanto pessoal quanto profissionalmente.",
    title: "Liderança Feminina na Tecnologia: Conquistando Espaço e Inspirando Transformação",
    companyTitle: "MáximaTech",
    social_media: {
      instagram: "https://www.instagram.com/kamilla.cerqueira/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/kamilla-cerqueira",
      github: "",
      website: "",
    },
  },
  {
    id: 6,
    path: "",
    photo: "/speakers/adrienneMendes.png",
    name: "Adrienne Mendes",
    tech: "Gestão de Projetos",
    topic: "",
    mini_bio: "Profissional com mais de 20 anos de experiência na área de gestão de projetos, negócios e educação. Especialista em Planejamento & Gestão de Projetos. Gestora com ênfase em Turismo & Hotelaria. Licenciada em Letras Português - Inglês. Certificada Scrum Master, White Belt e em Gestão Neurocomportamental de Projetos. Fluente em Inglês e Espanhol. Iniciou sua carreira como professora de idiomas (Inglês e Espanhol) na Educação Básica, EJA e Ensino Superiour. Atuou no Sistema S (Sesi, FIEG e Senac) como líder de projetos. Voluntária pelo PMI DF (gerente de projetos do programa de mentoring) e pelo PMI GO (membro do time do PM Thanks Mulher). Membro do Elas Projetam e do Mulheres GO.",
    title: "",
    companyTitle: "Ipasgo",
    social_media: {
      instagram: "https://www.instagram.com/adriennecmendes/",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/adrienne-mendes",
      github: "",
      website: "",
    },
  },
  {
    id: 7,
    path: "",
    photo: "/speakers/fernandaKelly.png",
    name: "Fernanda Kelly",
    tech: "Principal Statistician",
    topic: "",
    mini_bio: "Sou uma mulher preta. Uma mulher preta com coragem, sabe? Que é graduada em Estatística pela UFG, 'brincou' de fazer mestrado em Ciências da Computação pela mesma universidade, mas que acabou indo trabalhar na área da saúde e iniciou o mestrado em Sistemas Inteligentes e suas Aplicações na Saúde pela UFCSPA. Também sou fundadora de um capítulo da organização mundial R-Ladies e faço parte do time global da organização AI Inclusive. E sabe o que é bom nisso tudo? É que caminho caminho ao lado de grandes mulheres.",
    title: "",
    companyTitle: "Fundação Getulio Vargas",
    social_media: {
      instagram: "https://www.instagram.com/fernandakellyrs",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/fernanda-kelly-98a43b17a",
      github: "https://github.com/FernandaKelly",
      website: "https://www.fernandakellyrs.com/",
    },
  },
  {
    id: 8,
    path: "",
    photo: "/speakers/camisMoreira.png",
    name: "Camis Moreira",
    tech: "Senior Salesforce Developer",
    topic: "",
    mini_bio: "Camis é uma pessoa não binária, palestrante, educadora, líder de comunidade e especialista em E-commerce e Frontend. Atua como analista sênior na Object Edge e possui certificação Google Project Management, além de desempenhar um papel crucial na liderança de times e no desenvolvimento de pessoas na área tech, participando ativamente em projetos de grande escala nacionais e internacionais.",
    title: "",
    companyTitle: "Object Edge",
    social_media: {
      instagram: "https://www.instagram.com/camiiismoreira",
      twitter: "",
      linkedIn: "https://www.linkedin.com/in/camismoreira",
      github: "",
      website: "https://linktr.ee/camismoreira",
    },
  },
  {
    id: 9,
    path: "",
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "",
    topic: "",
    mini_bio: "",
    title: "",
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
    },
  },
  // {
  //   id: 10,
  //   path: "",
  //   photo: "/speakers/aDefinir.png",
  //   name: "A definir",
  //   tech: "Minha tecnologia",
  //   topic: "Tópico da minha palestra",
  //   mini_bio: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur officiis architecto dignissimos sed, consequuntur magnam, praesentium dicta voluptates nulla libero ut harum placeat reiciendis nobis velit, sequi facilis. Temporibus, sunt.",
  //   title: "Título da minha palestra",
  //   companyTitle: "Nome da minha empresa",
  //   social_media: {
  //     instagram: "https://www.instagram.com/gdggoiania/",
  //     twitter: "https://twitter.com/gdggoiania",
  //     linkedIn: "https://www.linkedin.com/company/gdggoiania/",
  //     github: "https://gitub.com/gdggoiania",
  //     website: "https://gdg.community.dev/gdg-goiania/",
  //   },
  // },
];

export default speakers;
